# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72692207fd7ffd26e487b5ac075db7db15fd37c838af49705856d9884355426e3825bead8a7adf1e059bc2c9f338eca70b0fd683d85cd91f8c8c0770b86fd27c

test:
  secret_key_base: a4059bb20dc45cbaab74bf6169ada5debc88711dda6a77714896dab834d6a3a05a43c4cddfaee8cfe9e53ccc0c3eb20f221e1943f9e297c2513d25d5bcc4dd6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
